steps:
#Build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/node-web-app:$COMMIT_SHA', '.']

#Push docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/node-web-app:$COMMIT_SHA']

#change image of deployment
- name: 'gcr.io/gcloud-builder/kubectl'
  args: ['set', 'image', 'deployment/mydeployment', 'mynode=gcr.io/theta-messenger-388512/node-web-app:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'